using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;

namespace VisualStudioTranslator.Vsix.Service;

/// <summary>
/// Starts the Engine process. This is a deliberately minimal, development-time
/// implementation: it launches the sibling project's own build output directly and does
/// not yet manage a single shared instance, versioned deployment under %LOCALAPPDATA%,
/// or idle shutdown - all of that is a later commit, once the RPC round trip itself is
/// confirmed to work end to end from inside Visual Studio.
/// </summary>
internal static class ServiceLauncher
{
    private const string DevelopmentEnginePathMetadataKey = "DevelopmentEnginePath";

    public static Process Start()
    {
        string enginePath = ResolveDevelopmentEnginePath();

        if (!File.Exists(enginePath))
        {
            throw new FileNotFoundException(
                "Engine executable not found. Build VisualStudioTranslator.Engine before debugging the Vsix project.",
                enginePath);
        }

        ProcessStartInfo startInfo = new(enginePath)
        {
            UseShellExecute = false,
            CreateNoWindow = true,
            WorkingDirectory = Path.GetDirectoryName(enginePath)!,
        };

        return Process.Start(startInfo)
            ?? throw new InvalidOperationException("Failed to start the Engine process.");
    }

    /// <summary>
    /// Locates VisualStudioTranslator.Engine.exe using an absolute path baked into this
    /// assembly at build time (see the AssemblyMetadata item in
    /// VisualStudioTranslator.Vsix.csproj). A path derived at runtime from
    /// Assembly.Location does not work here: once deployed, this assembly runs from the
    /// experimental hive's extension folder, not from its original bin output, so any
    /// relative walk from there no longer lands anywhere near the repository - which is
    /// exactly what just happened.
    /// </summary>
    private static string ResolveDevelopmentEnginePath()
    {
        string? path = typeof(ServiceLauncher).Assembly
            .GetCustomAttributes<AssemblyMetadataAttribute>()
            .FirstOrDefault(a => a.Key == DevelopmentEnginePathMetadataKey)
            ?.Value;

        // string.IsNullOrEmpty is not [NotNullWhen]-annotated on net48's own BCL, so the
        // compiler cannot narrow `path` to non-null through it the way it would on a
        // modern TFM. An explicit `is null` check narrows through plain C# flow analysis
        // instead, which does not depend on BCL attributes at all.
        if (path is null || path.Length == 0)
        {
            throw new InvalidOperationException(
                $"Assembly metadata '{DevelopmentEnginePathMetadataKey}' was not found. " +
                "This is generated by VisualStudioTranslator.Vsix.csproj at build time.");
        }

        return path;
    }
}